server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: pm-ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/pm_ecommerce
    username: postgres
    password: secret_password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:db/liquibase/changelog.xml
