server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: local
  application:
    name: pm-ecommerce

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    ru.sfera.pm.ecommerce: DEBUG
  file:
    name: logs/ecommerce.log